-- MySQL Script generated by MySQL Workbench
-- Tue Jan 17 18:07:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ventasReg
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ventasReg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ventasReg` DEFAULT CHARACTER SET utf8 ;
USE `ventasReg` ;

-- -----------------------------------------------------
-- Table `ventasReg`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventasReg`.`cargos` (
  `idcargo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `descripcion` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`idcargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventasReg`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventasReg`.`usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT CURRENT_TIMESTAMP,
  `apellido` VARCHAR(45) NULL,
  `fechaNaci` DATE NULL,
  `fechaIngreso` DATE NULL,
  `documento` VARCHAR(45) NULL,
  `cargo` INT NULL,
  INDEX `idcargo_id_idx` (`cargo` ASC) VISIBLE,
  PRIMARY KEY (`idUsuarios`),
  CONSTRAINT `idcargo_id`
    FOREIGN KEY (`cargo`)
    REFERENCES `ventasReg`.`cargos` (`idcargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ventasReg`.`tipo_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventasReg`.`tipo_productos` (
  `idtipo_productos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipo_productos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventasReg`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventasReg`.`compra` (
  `idproductos` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `usuario_ingreso` INT NOT NULL,
  `tipo` INT NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `marca` VARCHAR(100) NOT NULL,
  `modelo` VARCHAR(70) NOT NULL,
  `precioCompra` FLOAT NOT NULL,
  `precioVenta` FLOAT NOT NULL,
  `cantidad` INT NOT NULL,
  `totalcompra` FLOAT NOT NULL,
  PRIMARY KEY (`idproductos`),
  INDEX `tipo_productos_fk_idx` (`tipo` ASC) VISIBLE,
  INDEX `ingreso_productrs_fk_idx` (`usuario_ingreso` ASC) VISIBLE,
  CONSTRAINT `tipo_productos_fk`
    FOREIGN KEY (`tipo`)
    REFERENCES `ventasReg`.`tipo_productos` (`idtipo_productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ingreso_productrs_fk`
    FOREIGN KEY (`usuario_ingreso`)
    REFERENCES `ventasReg`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventasReg`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventasReg`.`detalle_venta` (
  `idDetalle` INT NOT NULL,
  `codigo` VARCHAR(45) NULL,
  `producto` INT NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  `dscto` VARCHAR(45) NULL,
  `cantidad` VARCHAR(45) NULL,
  `total` VARCHAR(45) NULL,
  PRIMARY KEY (`idDetalle`),
  INDEX `producto_fk_idx` (`producto` ASC) VISIBLE,
  CONSTRAINT `producto_fk`
    FOREIGN KEY (`producto`)
    REFERENCES `ventasReg`.`compra` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventasReg`.`tipo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventasReg`.`tipo_pago` (
  `idtipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idtipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventasReg`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventasReg`.`venta` (
  `idventa` INT NOT NULL AUTO_INCREMENT,
  `id_detalle` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `cliente_name` VARCHAR(45) NULL,
  `documento` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `total` VARCHAR(45) NULL,
  `tipo_pago` INT NOT NULL,
  PRIMARY KEY (`idventa`),
  INDEX `detalle_fk_idx` (`id_detalle` ASC) VISIBLE,
  INDEX `tipo_pago_fk_idx` (`tipo_pago` ASC) VISIBLE,
  CONSTRAINT `detalle_fk`
    FOREIGN KEY (`id_detalle`)
    REFERENCES `ventasReg`.`detalle_venta` (`idDetalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipo_pago_fk`
    FOREIGN KEY (`tipo_pago`)
    REFERENCES `ventasReg`.`tipo_pago` (`idtipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
